blank_issues_enabled: false
contact_links:
  - name: Read the community guidelines
    about: "Please make sure you have read the submission guidelines before posting an issue"
    url: https://github.com/BlackBeltTechnology/judo-community/blob/develop/CONTRIBUTING.adoc#-submitting-an-issue
  - name: Want to start a discussion?
    about: "Want to start a thread to discuss an idea? Use the discussions feature provided by GitHub."
    url: https://github.com/BlackBeltTechnology/judo-community/discussions
  - name: Have a question?
    url: https://discord.com/channels/918892501434241054
    about: "The Community Discord is a great place for questions to be asked and answered."
